"""RLM (Recursive Language Model) request/response models."""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field

from src.models.retrieval import CamelCaseModel


class RlmToolCall(CamelCaseModel):
    """A single tool call made during an RLM iteration."""

    tool: str  # "rag_retrieve", "mongo_fetch", "sub_rlm"
    args: dict[str, Any] = Field(default_factory=dict)
    result_summary: str = ""
    duration_ms: float = 0.0


class RlmIteration(CamelCaseModel):
    """A single iteration of the RLM control loop."""

    iteration: int
    code: str  # Code generated by the LLM
    stdout: str = ""  # Stdout from REPL execution
    state_changes: dict[str, str] = Field(default_factory=dict)  # Variable name → summary
    tool_calls: list[RlmToolCall] = Field(default_factory=list)
    model_used: str = ""
    tokens_used: int = 0
    duration_ms: float = 0.0
    error: Optional[str] = None


class RlmSubCall(CamelCaseModel):
    """Metadata for a sub_RLM recursive call."""

    depth: int
    prompt_preview: str = ""  # First 200 chars of sub prompt
    iterations_used: int = 0
    model_used: str = ""
    tokens_used: int = 0
    duration_ms: float = 0.0
    result_preview: str = ""  # First 200 chars of result


class RlmTrace(CamelCaseModel):
    """Full execution trace for an RLM run."""

    iterations: list[RlmIteration] = Field(default_factory=list)
    sub_calls: list[RlmSubCall] = Field(default_factory=list)
    total_llm_calls: int = 0
    total_tokens: int = 0
    total_rag_calls: int = 0
    max_depth_reached: int = 0


class RlmExecuteRequest(BaseModel):
    """Request body for the /rlm/execute endpoint."""

    query: str
    engagement_id: str
    context: str = ""  # Optional pre-fetched context from the agentic planner
    max_iterations: Optional[int] = None  # Override config default
    max_depth: Optional[int] = None  # Override config default
    app_mode: str = "audit"  # "audit" | "legal" | "compliance"


class RlmStatus(str, Enum):
    """Status of an RLM execution."""

    COMPLETED = "completed"
    MAX_ITERATIONS = "max_iterations"
    KILLED = "killed"
    ERROR = "error"
    TIMEOUT = "timeout"


class RlmExecuteResponse(CamelCaseModel):
    """Response from the /rlm/execute endpoint."""

    answer: str
    citations: list[dict[str, Any]] = Field(default_factory=list)  # Reuses Citation-like dicts
    confidence: float = 0.0
    status: RlmStatus = RlmStatus.COMPLETED
    iterations_used: int = 0
    sub_calls_used: int = 0
    total_tokens: int = 0
    # Mirrored at the top level so NestJS can read it flat without digging into `trace`.
    max_depth_reached: int = 0
    trace: RlmTrace = Field(default_factory=RlmTrace)
    duration_ms: float = 0.0
    started_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    error: Optional[str] = None
